# This needs to be fixed...

name: build

on:
  push:
  workflow_dispatch:
  pull_request:
    types: [opened, reopened]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: corretto

      - name: Cache Gradle packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*','**/gradle-wrapper.properties') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Clean
        run: ./gradlew clean

      - name: Build
        run: ./gradlew build

      # this MIGHT fix the weird mixin shadow fields obfuscation
      # idk tho
      - name: Build 2 electric boogaloo
        run: ./gradlew build

      - uses: actions/upload-artifact@v4
        with:
          name: Paragon-Build
          path: build/libs/*.jar

      - name: Cleanup Gradle Cache
        run: |
          rm -rf ~/.gradle/caches/modules-2/modules-2.lock
          rm -rf ~/.gradle/caches/modules-2/gc.properties
